number = int(input("Enter random number from 1-30: "))
#odd = კენტი, even = ლუწი
if number == 1:
    print("this number is Odd")
elif number == 2:
    print("this number is even")
elif number == 3:
    print("this number is odd")
elif number == 4:
    print("this number is even")
elif number == 5:
    print("this number is odd")
elif number == 6:
    print("this number is even")
elif number == 7:
    print("this number is odd")
elif number == 8:
    print("this number is even")
elif number == 9:
    print("this number is odd")
elif number == 10:
    print("this number is even")
elif number == 11:
    print("this number is odd")
elif number == 12:
    print("this number is even")
elif number == 13:
    print("this number is odd")
elif number == 14:
    print("this number is even")
elif number == 15:
    print("this number is odd")
elif number == 16:
    print("this number is even")
elif number == 17:
    print("this number is odd")
elif number == 18:
    print("this number is even")
elif number == 19:
    print("this number is odd")
elif  number == 20:
    print("this number is even")
elif number == 21:
    print("this number is odd")
elif number == 22:
    print("this number is even")
elif number == 23:
    print("this number is odd")
elif number == 24:
    print("this number is even")
elif number == 25:
    print("this number is odd")
elif number == 26:
    print("this number is even")
elif number == 27:
    print("this number is odd")
elif number == 28:
    print("this number is even") 
elif number == 29:
    print("this number is odd")
elif number == 30:
    print("this number is even")                